name: WabotAutoDeploy

on:
  push:
    branches:
      - main  # Trigger saat push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_BACKEND }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_IP_BACKEND }} >> ~/.ssh/known_hosts

    - name: Deploy to Server via Docker Compose
      run: |
        ssh ${{ secrets.SSH_USER_BACKEND }}@${{ secrets.SSH_IP_BACKEND }} << 'EOF'

          echo "ðŸ“ Masuk ke direktori WaBot"
          cd /home/ecustomer/WaBot

          echo "â™»ï¸ Reset perubahan lokal..."
          git reset --hard origin/main
          git clean -fd

          echo "â¬‡ï¸ Menarik pembaruan dari Git..."
          git pull origin main

          echo "ðŸ³ Menjalankan ulang dengan Docker Compose..."
          docker-compose down
          docker-compose up -d --build

          echo "ðŸ§¹ Membersihkan image yang tidak terpakai..."
          docker system prune -af

          DEPLOY_TIME=$(date +"%A, %d-%m-%Y %H:%M:%S")
          echo "âœ… Deployment selesai pada $DEPLOY_TIME"
        EOF

        # name: WabotAutoDeploy
